In [1]:
import numpy as np

a = np.random.randn(5)
print(a)

[ 0.12142101  1.22951512 -0.92103275 -0.6559782  -0.06903925]


In [2]:
print(a.shape)

(5,)


In [3]:
a = np.random.rand(5,1)
print(a)

[[0.25069289]
 [0.31617557]
 [0.24412128]
 [0.55114136]
 [0.06495214]]


In [4]:
print(a.T)

[[0.25069289 0.31617557 0.24412128 0.55114136 0.06495214]]


주의할점 : m x 1 벡터를 만들 때 **Rank 1** (m, ) 형태로 만들지 말라.\
(m,1) 형태로 만들 것\
이유 : 행렬 전치가 안되고, np.dot(내적)을 할 경우에 제대로 되지 않음.

In [6]:
img = np.ones((32*32,3))
print(img)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 ...
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
a = np.random.randn(3,3)

b = np.random.randn(3,1)

c = a * b
print(c)

[[ 0.38585064  0.49968374 -0.2622756 ]
 [ 1.3160487  -1.23209341  0.40326276]
 [-0.28247153 -0.12632802  0.03317677]]
